name: Trigger git submodule update in the docs repo

on:
  push:
    branches:
      - add-workflow-docs-notification
  workflow_dispatch:

jobs:
  update_submodule_in_docs_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger git submodule update in the docs repo
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PARENT_REPO: wallarm/product-documentation
          WORKFLOW_ID: 7113795232
        
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ env.PARENT_REPO }}/actions/workflows/${{ env.WORKFLOW_ID }}/dispatches \
            -d '{}'
